execution_units:
  executor-1:
    type: lambda
  executor-2:
    type: lambda
  task-1:
    type: lambda
  task-2:
    type: ecs
  task-3:
    type: eks
static_unit:
  static-unit:
    content_delivery_network:
      id: static-unit-cdn
